Верстка шапки: навигация и херо блок
iglv/yard-frontend pull request #1
Opened 2017-06-26 13:21 UTC by iglv

Хочу получить обратную связь для продолжения.

2017-06-26 17:26 UTC, evgenyrodionov commented
Коммиты должны быть на английском
Сделай полностью, после этого вешай на ревью

2017-06-26 17:27 UTC, evgenyrodionov commented
Кодстайл не соблюдается

2017-06-27 14:26 UTC, imevro requested changes
табы на два пробела переделать

2017-06-27 14:44 UTC, iglv commented
Переделал

2017-06-27 23:24 UTC, imevro submitted a review, later dismissed

2017-06-27 23:24 UTC, evgenyrodionov commented on complexes.html
> +    <link href="http://code.cdn.mozilla.net/fonts/fira.css" rel="stylesheet">
лучше фонтс.гугл.ком, это стандартнее выбор

2017-06-27 23:24 UTC, evgenyrodionov commented on complexes.html
> +    <link rel="stylesheet" href="styles/normalize.css">
попробуй подключить из cdnjs

2017-06-27 23:24 UTC, evgenyrodionov commented on complexes.html
> +        <a href="#"><img src="img/compass-development-logo.svg" alt="Development"></a>
это не ссылка

2017-06-27 23:24 UTC, evgenyrodionov commented on complexes.html
> +        <div class="cards__item">
в чем смысл этого дива поверх ссылки?

2017-06-27 23:24 UTC, evgenyrodionov commented on styles/style.css
> +.container {
почему? в фбг свой контейнер

2017-06-27 23:24 UTC, evgenyrodionov commented on styles/style.css
> +  font-size: 62.5%;
объясни

2017-06-27 23:24 UTC, evgenyrodionov commented on styles/style.css
> +    float: right;
без флоатов

2017-06-27 23:24 UTC, evgenyrodionov commented on styles/style.css
> +  .links {
.header__links и .links? не вижу согласованности

2017-06-28 12:38 UTC, iglv commented on styles/style.css
> +  font-size: 62.5%;
Для удобства. Потом 4.8rem = 48 px

2017-06-28 12:42 UTC, iglv commented on styles/style.css
> +  .links {
. links может быть еще где-нибудь в проекте использоваться, поэтому он как отдельный блок.

2017-06-28 18:19 UTC, evgenyrodionov commented
https://rawgit.com/iglv/yard-frontend/develop/complexes.html


![image](https://user-images.githubusercontent.com/775692/27653131-cf40357a-5c46-11e7-8842-950d65f3f6db.png)
![image](https://user-images.githubusercontent.com/775692/27653165-de5a5a72-5c46-11e7-8f92-8bffb302f478.png)
![image](https://user-images.githubusercontent.com/775692/27653175-eac479c8-5c46-11e7-820b-4422e30953bd.png)

2017-06-29 08:38 UTC, iglv commented
Проблема была с контейнером

2017-06-29 10:39 UTC, imevro requested changes

2017-06-29 10:39 UTC, evgenyrodionov commented on styles/style.css
> +.container {
и все же

2017-06-29 10:39 UTC, evgenyrodionov commented on styles/style.css
> +  .links {
ровно в таком же стиле?

2017-06-29 10:39 UTC, evgenyrodionov commented on complex.html
> +<head>
убирай отсюда комплекс.хтмл, он в отдельном бранче делается

2017-06-29 10:39 UTC, evgenyrodionov commented on complex.html
> +<head>
бтв тут опять табы вместо 2 пробелов

2017-06-29 13:15 UTC, imevro requested changes

2017-06-29 13:15 UTC, evgenyrodionov commented on styles/style.css
> +.container {
В ОЧЕРЕДНОЙ РАЗ СПРАШИВАЮ ЗАЧЕМ ЭТОТ КЛАСС ТУТ

2017-06-29 13:15 UTC, evgenyrodionov commented on styles/style.css
> +  .links {
а также вопрос — ты уверен, что на сайте будут ссылки ровно в таком же стиле?

2017-06-30 21:58 UTC, iglv commented on styles/style.css
> +  .links {
не понял вопроса, это про ссылки на которые я навожу курсор?

2017-07-01 09:29 UTC, imevro approved these changes

2017-07-03 09:30 UTC, merged