React components
iglv/yard-frontend pull request #5
Opened 2017-07-04 08:58 UTC by iglv

2017-07-04 17:52 UTC, imevro requested changes

2017-07-04 17:52 UTC, evgenyrodionov commented on src/Complexes/Cards.js
> +import React from 'react';
а зачем эта прокладка

2017-07-04 17:52 UTC, evgenyrodionov commented on src/Complexes/Index.js
> +import React, { Component } from 'react';
во-первых с маленькой буквы
во вторых почему это лежит не в List

2017-07-04 17:52 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +import ComplexInfo from './Info';
зачем этот префикс комплекс если я и так нахожусь в Complex/View?

2017-07-04 17:52 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +import ComplexSpec from './Spec';
Spec? что за экономия?

2017-07-04 17:52 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +import ComplexAvailable from './Available';
почему прилагательным?

2017-07-04 17:52 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +        <div className="App">
почему .App?

2017-07-04 19:06 UTC, iglv commented on src/Complexes/Index.js
> +import React, { Component } from 'react';
Index должен лежать в List?

2017-07-06 10:01 UTC, iglv commented on src/Complexes/View/Index.js
> +import ComplexAvailable from './Available';
available — наличие

2017-07-06 17:15 UTC, evgenyrodionov commented on src/Complexes/Index.js
> +import React, { Component } from 'react';
Ну да, ты же тут список отображаешь

2017-07-06 17:24 UTC, imevro requested changes
нихуя не понял что мне проверять, дальше и не стал

2017-07-06 17:24 UTC, evgenyrodionov commented on public/index.html
>      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
из нпма

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/Btn.js
> +&:hover,
поставь преттир

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/Btn.js
> +
что за лошадиные пустые строки

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/Btn.js
> +class Btn extends Component {
зачем вообще этот компонент-прокладка? Экспорти сразу стайледкомпонент

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/Btn.js
> +const BtnStyled = styled.a`
Btn = a? Как-то неочевидно

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/Card.js
> +class Card extends Component {
зачем сделал классом вместо функции?

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/Hero.js
>        <div className="container">
почему не фбг

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/List/Headline.js
> +        <HeadlineTitle>Discover Our New Developments</HeadlineTitle>
читай чужие пры

2017-07-06 17:24 UTC, evgenyrodionov commented on src/Complexes/View/Available.js
> +        <div className="compex-available">
смысл кидать ПР если ты не доделал?

2017-07-08 10:54 UTC, imevro requested changes

2017-07-08 10:54 UTC, evgenyrodionov commented on src/App.js
> +import Complexes from './Complexes/List/Index'
переименуй Индекс в index и импорти как `from './Complexes/List`. Вебпак по-умолчанию ищет файлы `index.js` и `index.jsx`

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +class Card extends Component {
сделай функциональным компонентом

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +      <CardStyled to="/сomplex">
обязательно стулед постфикс?

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Available.js
> +const Item = styled.div`
слишком общий нейминг

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Available.js
> +const AvailableStyled = styled.div`
почему available вообще компонент называется? втф?

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Available.js
> +const AvailableStyled = styled.div`
логика в чем?

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Desc.js
> +        <DescStyled>
Да хватит экономить на байтах

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Desc.js
> +        <DescStyled>
Row лежит в контейнере обычно

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Desc.js
> +        <DescStyled>
логичнее твой дескрипшен (а можно просто враппер) поставить на топ-уровень

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
> +const Url = styled(Link)`
что за урл? почитай определение https://en.wikipedia.org/wiki/URL

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
> +const Url = styled(Link)`
компонент явно не может урлом называться

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
>              <img className="complex-guide__photo" src="img/polyanka-photo.png" srcSet="img/polyanka-photo@3x.png 2x,
с хуя ли тут класснейм если у тебя стайлед?

2017-07-08 10:54 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
>              <img className="complex-guide__photo" src="img/polyanka-photo.png" srcSet="img/polyanka-photo@3x.png 2x,
дальше не проверяю, работа не выглядит законченной

2017-07-08 17:22 UTC, evgenyrodionov commented on src/Complexes/List/Index.js
> +        <Card location="SOUTH BEACH, SAN FRANCISCO" title="764 Metropolitan Avenue" description="The Lewis Steel Building is a masterful industrial conversion located in the heart of Williamsburg. Lo
читай чужие пры

2017-07-08 17:22 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
> +          <Subtitle>{props.subtitle}</Subtitle>
сабтайтл выше тайтла, вау

2017-07-08 17:22 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +      <Available sentences="950" architect="John McAslan + Partners" developer="Группа «ПСН»" />
и что это за аваилабле?

2017-07-08 17:22 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +      <Photos></Photos>
преттир поставь

2017-07-08 17:22 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
>         text-align: center;
что стало тут с отступами

2017-07-08 17:22 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +const StyledH2 = styled.div`
Что с неймингом раз, с хуя ли H2 это див, два

2017-07-08 21:41 UTC, imevro requested changes

2017-07-08 21:41 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +const Location = styled.div`
почему див вообще

2017-07-08 21:41 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +const Title = styled.h1`
а тут почему h1-то бля

2017-07-08 21:41 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
> +const Locate = styled.div`
И с хуя ли в названии компонента глагол

2017-07-08 21:41 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +      <Photos></Photos>
ну и?

2017-07-09 22:10 UTC, imevro requested changes

2017-07-09 22:10 UTC, evgenyrodionov commented on package.json
> +    "get-stdin": "^5.0.1",
что это вообще

2017-07-09 22:10 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
> +          <Location>
не разноси на три строчки бля в чужих пуллреквестах тысячу раз об этом писал

2017-07-09 22:10 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +        sentences="950"
предложения тут как предложения клиенту, а не как предложения из грамматики

2017-07-09 22:10 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +        map="polyanka-photo.png"
Зачем это пропом ппередавать

2017-07-09 22:10 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +        map="polyanka-photo.png"
зачем тут вообще что-либо пропом передавать

2017-07-09 22:10 UTC, evgenyrodionov commented on src/Complexes/View/Map.js
> +  const content = props.list.map(photo =>
не заводи отдельную константу под мап, сразу делай мап там где он нужен

2017-07-09 22:10 UTC, evgenyrodionov commented on src/Complexes/View/Map.js
> +  const content = props.list.map(photo =>
list хуевый нейминг

2017-07-09 22:10 UTC, evgenyrodionov commented on src/Complexes/View/Offer.js
> +      {props.room}-комнатные квартиры
рум? слабый нейминг

2017-07-10 09:14 UTC, imevro requested changes

2017-07-10 09:14 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
> +            src="polyanka-photo.png"
передавай сразу адрес картинки, а не вот это

2017-07-10 09:14 UTC, evgenyrodionov commented on src/Complexes/View/Index.js
> +        offers="950"
не строкой

2017-07-10 09:14 UTC, evgenyrodionov commented on src/Complexes/View/Map.js
>  const locationList = [
можно просто locations

2017-07-10 09:14 UTC, evgenyrodionov commented on src/Complexes/View/Photos.js
> +      {photoList.map(({ url, caption }, index) =>
`photos` или `images`

2017-07-10 10:48 UTC, imevro requested changes

2017-07-10 10:48 UTC, evgenyrodionov commented on src/Complexes/View/Guide.js
> +          <ImageGuide src="polyanka-photo.png" alt="Полянка" />
да не название файла передавай, а адрес файла

2017-07-10 10:48 UTC, evgenyrodionov commented on src/Complexes/View/Photos.js
> +const total = images.length;
смысл память забивать отдельной константой

2017-07-10 13:00 UTC, imevro approved these changes

2017-07-10 13:00 UTC, merged