Api
iglv/yard-frontend pull request #7
Opened 2017-07-14 10:03 UTC by iglv

2017-07-14 17:12 UTC, evgenyrodionov commented
Как тестить? Где деплой?

2017-07-14 17:42 UTC, iglv commented
https://build-ijszmfftrf.now.sh

2017-07-14 22:09 UTC, iglv commented
https://build-kstaefpbgf.now.sh

2017-07-14 23:34 UTC, evgenyrodionov commented
Что с версткой стало? Вообще не по макету распидорасило

![image](https://user-images.githubusercontent.com/775692/28234233-0992f700-6906-11e7-92f7-71a36e4715c4.png)

2017-07-14 23:34 UTC, evgenyrodionov commented
Тут шрифты сломались
![image](https://user-images.githubusercontent.com/775692/28234241-249e3bea-6906-11e7-82b8-b852d2d15186.png)

2017-07-14 23:34 UTC, evgenyrodionov commented
«Описание not found» это какой-то пиздец для посетителя сайта

2017-07-14 23:35 UTC, evgenyrodionov commented
Не смог прокинуть название ЖК?

![image](https://user-images.githubusercontent.com/775692/28234246-34dcec2c-6906-11e7-97a6-43cfaefffaf7.png)

2017-07-15 09:36 UTC, iglv commented
https://build-vnrdqdgwxb.now.sh

2017-07-15 13:18 UTC, imevro requested changes
не вижу исправления шрифтов

2017-07-15 13:19 UTC, evgenyrodionov commented
А также что это за полоса
![image](https://user-images.githubusercontent.com/775692/28239634-4eac8018-6979-11e7-98ac-f5c555c4b2ba.png)

2017-07-15 13:19 UTC, evgenyrodionov commented
И что это за дыра

![image](https://user-images.githubusercontent.com/775692/28239635-6a3ba3e0-6979-11e7-9058-eaeb7d00be50.png)

2017-07-15 13:20 UTC, evgenyrodionov commented
Больше внимательности, блядь, а потом начнешь в 12 "ну я же старался"

2017-07-15 14:18 UTC, iglv commented
https://build-dggvmtjvtr.now.sh

2017-07-15 14:22 UTC, iglv commented
https://build-hmkziwqyeb.now.sh

2017-07-15 17:37 UTC, evgenyrodionov commented
Я не проверяю ПР если есть коммиты после реквеста ревью

2017-07-15 17:37 UTC, evgenyrodionov commented
бтв нихуя шрифты не работают

2017-07-15 17:38 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28241461-9315c8d0-699d-11e7-9b27-677dc58fb4ff.png)

2017-07-15 17:38 UTC, evgenyrodionov commented
И почему впритык заканчивается блок с хар-ками

2017-07-15 18:45 UTC, iglv commented
https://build-woqgewzjpr.now.sh

2017-07-15 21:00 UTC, evgenyrodionov commented
Прочитай чужие ПРы на тему высоты потолков и начала/конца строительства

![image](https://user-images.githubusercontent.com/775692/28242640-b0780ec6-69b9-11e7-9b6d-192197f369e3.png)

2017-07-15 21:06 UTC, imevro requested changes

2017-07-15 21:06 UTC, evgenyrodionov commented on src/App.js
> +      <Route exact path="/complex/:slug" component={Complex} />
плохая архитектура роутов

2017-07-15 21:06 UTC, evgenyrodionov commented on src/App.js
> +      <Route exact path="/complex/:slug" component={Complex} />
надо по бизнес логике

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +        src={`https://yard-images.s3.amazonaws.com/${props.image}-1024`}
1024 при максимальной высоте 352? пиздец

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +        src={`https://yard-images.s3.amazonaws.com/${props.image}-1024`}
браузеру нужно в 3 раза сжать пикчу

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +        src2x={`https://yard-images.s3.amazonaws.com/${props.image}-1024`}
почему тут тоже 1024?

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +        src3x={`https://yard-images.s3.amazonaws.com/${props.image}-1024`}
и тут?

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +    const url = 'https://yard.moscow/api/v1/complexes?filter%5Bstate%5D=public';
читай чужие пры

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +      items: [],
читай чужие пры

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +        {this.state.items.map(post =>
какой пост?

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +      <CardsStyled>
зачем постфикс Styled? У тебя есть Cards без styled?

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/Description.jsx
> +  if (props.children) {
conditional rendering

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/Guide.jsx
> +              alt="{props.locality}"
посмотри во что оно превратилось

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/Infrastructure.jsx
> +  if (props.amenity) {
пиздишь чужой код видно

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/Infrastructure.jsx
> +  if (props.amenity) {
ошибка та же самая

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/Special.jsx
> +                {details.parking > 0 && `${details.parking} м/м`}
если будет указано 0, то что?

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/Summary.jsx
> +          {props.offers &&
чего? выведет 0 без сабтайтла?

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/Summary.jsx
> +            <Subtitle>архитектор</Subtitle>
а тут undefined вместо архитектора и без сабтайтла тоже

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/index.jsx
> +    const amenities = this.state.complex.amenities || {};
дестрактом это все доставай

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/index.jsx
> +            offers={statistics.propertiesCount}
offers={propertiesCount}? где согласованность

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/index.jsx
> +    const description = this.state.complex.description;
такого поля вообще-то нет в модели

2017-07-15 21:06 UTC, evgenyrodionov commented on src/Complexes/View/index.jsx
> +          <Guide locality={location.subLocalityName} />
locality={subLocalityName}?

2017-07-16 13:07 UTC, iglv commented
https://build-kiqmmmxerd.now.sh

2017-07-17 10:09 UTC, imevro requested changes

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/View/Infrastructure.jsx
> +  const amenities = props.complex.amenities || [];
дестрактом

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/View/Special.jsx
> +                От {Math.floor(totalPrimaryAreaFrom).toFixed(1)} до&nbsp;
в функцию вынеси

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/View/Special.jsx
> +                {details.undergroundGarages > 0 &&
КОГДА БУДЕТ НОЛЬ, ВО ЧТО ОНО ОТРАБОТАЕТСЯ?

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/View/Summary.jsx
> +            <div>
с хуя ли див

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/View/Summary.jsx
>          <Title>
зачем вообще рендерить блок если нет пропертиескаунт?

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/View/index.jsx
> +            <div>
зачем тут див

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/get.jsx
> +  // For debug
убери этот мусор

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/get.jsx
> +// TODO: Удалить правило выше
комментарии на английском

2017-07-17 10:09 UTC, evgenyrodionov commented on src/Complexes/get.jsx
> +// TODO: Удалить правило выше
напиши когда удалить это правило-то

2017-07-17 17:07 UTC, imevro requested changes

2017-07-17 17:07 UTC, evgenyrodionov commented on src/Complexes/View/Infrastructure.jsx
> +  } = props.complex || [];
комплекс  это объект, а не массив, это раз
можно сразу в параметре функции делать дестракт, два

2017-07-17 21:01 UTC, imevro requested changes

2017-07-17 21:01 UTC, evgenyrodionov commented on src/Complexes/View/index.jsx
> +              <Infrastructure complex={amenities} />
complex={amenities}? wtf?

2017-07-17 21:01 UTC, evgenyrodionov commented on src/Complexes/View/index.jsx
> +            <div>
и опять же нахуй див

2017-07-18 11:19 UTC, imevro requested changes

2017-07-18 11:19 UTC, evgenyrodionov commented on src/Complexes/View/Infrastructure.jsx
> +export default ({ amenities = [] }) =>
если ты передаешь комплекс, то откуда будет аменитис в пропах, БЛЯДЬ

2017-07-19 09:50 UTC, merged